version: '3.9'

services:
  db:
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
